title: "M.A.X. Port"
description: >-
  M.A.X. Port is a runtime executable for the 1996 DOS game M.A.X.: Mechanized Assault & Exploration developed and published by Interplay Productions.
author:
  name: M.A.X. Port Team
  github: klei1984/max
show_excerpts: true

remote_theme: "jekyll/minima@v2.5.1"
plugins:
  - jekyll-remote-theme
  - jekyll-feed

header_pages:
  "About": about.md
  "Evolution": evolution.md
  "Roadmap": roadmap.md
  "Articles ▼":
    - "Installation Guideline": install.md
    - "Frequently Asked Questions": faq.md
    - "Build Instructions": build.md
    - "Scripting Manual": scripting.md
    - "Patching Up MS-DOS Versions": fixdos.md
    - "Development Environments": devenv.md
    - "Documentation": documentation.md
    - "Save File Format": save.md
    - "Networking": network.md
  "License": license.md
  "Defects": defects.md
  "Download": download.md
