find_program(MAKENSIS_EXECUTABLE NAMES makensis DOC "The NSIS package maker command")
if(MAKENSIS_EXECUTABLE)
	list(APPEND CPACK_GENERATOR "NSIS")

	if(X86)
		set (CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
	elseif(X86_64)
		set (CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64")
	endif()

	set(CPACK_NSIS_DISPLAY_NAME "M.A.X. Port")
	set(CPACK_NSIS_PACKAGE_NAME "M.A.X. Port")

	if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Windows")
		set(CPACK_NSIS_BRANDING_TEXT " ")
	endif()

	set(CPACK_NSIS_EXECUTABLES_DIRECTORY ".")
	set(CPACK_NSIS_MANIFEST_DPI_AWARE TRUE)
	set(CPACK_NSIS_WELCOME_TITLE_3LINES TRUE)
	set(CPACK_NSIS_FINISH_TITLE_3LINES TRUE)
	set(CPACK_NSIS_MUI_ICON "${CMAKE_SOURCE_DIR}/assets/max.ico")
	set(CPACK_NSIS_CREATE_ICONS_EXTRA "${CPACK_NSIS_CREATE_ICONS_EXTRA}
		CreateShortCut '$SMPROGRAMS\\\\$STARTMENU_FOLDER\\\\M.A.X. Port.lnk' '$INSTDIR\\\\max.exe'
		CreateShortCut '$DESKTOP\\\\M.A.X. Port.lnk' '$INSTDIR\\\\max.exe'
	")
	set(CPACK_NSIS_DELETE_ICONS_EXTRA "${CPACK_NSIS_DELETE_ICONS_EXTRA}
		Delete '$SMPROGRAMS\\\\$MUI_TEMP\\\\M.A.X. Port.lnk'
		Delete '$DESKTOP\\\\M.A.X. Port.lnk'
	")
	set(CPACK_NSIS_MUI_FINISHPAGE_RUN "${PROJECT_NAME}")
	set(INCLUDE_FILE "${CMAKE_SOURCE_DIR}\\\\cmake\\\\nsis\\\\install.nsh")
	set(CPACK_NSIS_EXTRA_INSTALL_COMMANDS "!include ${INCLUDE_FILE}")
	set(CPACK_NSIS_PAGE_COMPONENTS "Page custom GameDataDirPageCreate GameDataDirPageLeave")
endif()
