#!/bin/sh -e
# Copyright: 2024 M.A.X. Port Team
# License: MIT

# Load dependencies
if ! [ -f "$1" ]; then exit 0; fi

maxport_configfile="$1"

FREETYPE_VERSION=$(sed -nr 's/set\(FREETYPE_VERSION ([0-9]+\.[0-9]+\.[0-9]+)\)/\1/p' $maxport_configfile)
FREETYPE_FILE=$(eval echo $(sed -nr 's/set\(FREETYPE_FILE (.*)\)/\1/p' $maxport_configfile))
FREETYPE_URI=$(eval echo $(sed -nr 's/set\(FREETYPE_URI (.*)\)/\1/p' $maxport_configfile))

MINIAUDIO_VERSION=$(sed -nr 's/set\(MINIAUDIO_VERSION ([0-9]+\.[0-9]+\.[0-9]+)\)/\1/p' $maxport_configfile)
MINIAUDIO_FILE=$(eval echo $(sed -nr 's/set\(MINIAUDIO_FILE (.*)\)/\1/p' $maxport_configfile))
MINIAUDIO_URI=$(eval echo $(sed -nr 's/set\(MINIAUDIO_URI (.*)\)/\1/p' $maxport_configfile))

SDL3_VERSION=$(sed -nr 's/set\(SDL3_VERSION ([0-9]+\.[0-9]+\.[0-9]+)\)/\1/p' $maxport_configfile)
SDL3_FILE=$(eval echo $(sed -nr 's/set\(SDL3_FILE (.*)\)/\1/p' $maxport_configfile))
SDL3_URI=$(eval echo $(sed -nr 's/set\(SDL3_URI (.*)\)/\1/p' $maxport_configfile))

ENET_VERSION=$(sed -nr 's/set\(ENET_VERSION ([0-9]+\.[0-9]+\.[0-9]+)\)/\1/p' $maxport_configfile)
ENET_FILE=$(eval echo $(sed -nr 's/set\(ENET_FILE (.*)\)/\1/p' $maxport_configfile))
ENET_URI=$(eval echo $(sed -nr 's/set\(ENET_URI (.*)\)/\1/p' $maxport_configfile))

MINIUPNP_VERSION=$(sed -nr 's/set\(MINIUPNP_VERSION ([a-z_0-9]+)\)/\1/p' $maxport_configfile)
MINIUPNP_FILE=$(eval echo $(sed -nr 's/set\(MINIUPNP_FILE (.*)\)/\1/p' $maxport_configfile))
MINIUPNP_URI=$(eval echo $(sed -nr 's/set\(MINIUPNP_URI (.*)\)/\1/p' $maxport_configfile))

GTEST_VERSION=$(sed -nr 's/set\(GTEST_VERSION ([0-9]+\.[0-9]+\.[0-9]+)\)/\1/p' $maxport_configfile)
GTEST_FILE=$(eval echo $(sed -nr 's/set\(GTEST_FILE (.*)\)/\1/p' $maxport_configfile))
GTEST_URI=$(eval echo $(sed -nr 's/set\(GTEST_URI (.*)\)/\1/p' $maxport_configfile))

SHA2_VERSION=$(sed -nr 's/set\(SHA2_VERSION ([a-z0-9]+)\)/\1/p' $maxport_configfile)
SHA2_FILE=$(eval echo $(sed -nr 's/set\(SHA2_FILE (.*)\)/\1/p' $maxport_configfile))
SHA2_URI=$(eval echo $(sed -nr 's/set\(SHA2_URI (.*)\)/\1/p' $maxport_configfile))

JSON_VERSION=$(sed -nr 's/set\(JSON_VERSION ([0-9]+\.[0-9]+\.[0-9]+)\)/\1/p' $maxport_configfile)
JSON_FILE=$(eval echo $(sed -nr 's/set\(JSON_FILE (.*)\)/\1/p' $maxport_configfile))
JSON_URI=$(eval echo $(sed -nr 's/set\(JSON_URI (.*)\)/\1/p' $maxport_configfile))

JSONSCHEMA_VERSION=$(sed -nr 's/set\(JSONSCHEMA_VERSION ([0-9]+\.[0-9]+\.[0-9]+)\)/\1/p' $maxport_configfile)
JSONSCHEMA_FILE=$(eval echo $(sed -nr 's/set\(JSONSCHEMA_FILE (.*)\)/\1/p' $maxport_configfile))
JSONSCHEMA_URI=$(eval echo $(sed -nr 's/set\(JSONSCHEMA_URI (.*)\)/\1/p' $maxport_configfile))

UTF8PROC_VERSION=$(sed -nr 's/set\(UTF8PROC_VERSION ([0-9]+\.[0-9]+\.[0-9]+)\)/\1/p' $maxport_configfile)
UTF8PROC_FILE=$(eval echo $(sed -nr 's/set\(UTF8PROC_FILE (.*)\)/\1/p' $maxport_configfile))
UTF8PROC_URI=$(eval echo $(sed -nr 's/set\(UTF8PROC_URI (.*)\)/\1/p' $maxport_configfile))

LUA_VERSION=$(sed -nr 's/set\(LUA_VERSION ([0-9]+\.[0-9]+\.[0-9]+)\)/\1/p' $maxport_configfile)
LUA_FILE=$(eval echo $(sed -nr 's/set\(LUA_FILE (.*)\)/\1/p' $maxport_configfile))
LUA_URI=$(eval echo $(sed -nr 's/set\(LUA_URI (.*)\)/\1/p' $maxport_configfile))

XOSHIRO_VERSION=$(sed -nr 's/set\(XOSHIRO_VERSION ([0-9]+\.[0-9]+)\)/\1/p' $maxport_configfile)
XOSHIRO_FILE=$(eval echo $(sed -nr 's/set\(XOSHIRO_FILE (.*)\)/\1/p' $maxport_configfile))
XOSHIRO_URI=$(eval echo $(sed -nr 's/set\(XOSHIRO_URI (.*)\)/\1/p' $maxport_configfile))

LZ4_VERSION=$(sed -nr 's/set\(LZ4_VERSION ([0-9]+\.[0-9]+\.[0-9]+)\)/\1/p' $maxport_configfile)
LZ4_FILE=$(eval echo $(sed -nr 's/set\(LZ4_FILE (.*)\)/\1/p' $maxport_configfile))
LZ4_URI=$(eval echo $(sed -nr 's/set\(LZ4_URI (.*)\)/\1/p' $maxport_configfile))

RECTPACK2D_VERSION=$(sed -nr 's/set\(RECTPACK2D_VERSION ([a-z0-9]+)\)/\1/p' $maxport_configfile)
RECTPACK2D_FILE=$(eval echo $(sed -nr 's/set\(RECTPACK2D_FILE (.*)\)/\1/p' $maxport_configfile))
RECTPACK2D_URI=$(eval echo $(sed -nr 's/set\(RECTPACK2D_URI (.*)\)/\1/p' $maxport_configfile))

RMLUI_VERSION=$(sed -nr 's/set\(RMLUI_VERSION ([0-9]+\.[0-9]+)\)/\1/p' $maxport_configfile)
RMLUI_FILE=$(eval echo $(sed -nr 's/set\(RMLUI_FILE (.*)\)/\1/p' $maxport_configfile))
RMLUI_URI=$(eval echo $(sed -nr 's/set\(RMLUI_URI (.*)\)/\1/p' $maxport_configfile))

[ -f "dependencies/$FREETYPE_FILE" ] || wget --no-clobber --quiet --output-document="dependencies/$FREETYPE_FILE" "$FREETYPE_URI" | true
[ -f "dependencies/$MINIAUDIO_FILE" ] || wget --no-clobber --quiet --output-document="dependencies/$MINIAUDIO_FILE" "$MINIAUDIO_URI" | true
[ -f "dependencies/$SDL3_FILE" ] || wget --no-clobber --quiet --output-document="dependencies/$SDL3_FILE" "$SDL3_URI" | true
[ -f "dependencies/$ENET_FILE" ] || wget --no-clobber --quiet --output-document="dependencies/$ENET_FILE" "$ENET_URI" | true
[ -f "dependencies/$MINIUPNP_FILE" ] || wget --no-clobber --quiet --output-document="dependencies/$MINIUPNP_FILE" "$MINIUPNP_URI" | true
[ -f "dependencies/$GTEST_FILE" ] || wget --no-clobber --quiet --output-document="dependencies/$GTEST_FILE" "$GTEST_URI" | true
[ -f "dependencies/$SHA2_FILE" ] || wget --no-clobber --quiet --output-document="dependencies/$SHA2_FILE" "$SHA2_URI" | true
[ -f "dependencies/$JSON_FILE" ] || wget --no-clobber --quiet --output-document="dependencies/$JSON_FILE" "$JSON_URI" | true
[ -f "dependencies/$JSONSCHEMA_FILE" ] || wget --no-clobber --quiet --output-document="dependencies/$JSONSCHEMA_FILE" "$JSONSCHEMA_URI" | true
[ -f "dependencies/$UTF8PROC_FILE" ] || wget --no-clobber --quiet --output-document="dependencies/$UTF8PROC_FILE" "$UTF8PROC_URI" | true
[ -f "dependencies/$LUA_FILE" ] || wget --no-clobber --quiet --output-document="dependencies/$LUA_FILE" "$LUA_URI" | true
[ -f "dependencies/$XOSHIRO_FILE" ] || wget --no-clobber --quiet --output-document="dependencies/$XOSHIRO_FILE" "$XOSHIRO_URI" | true
[ -f "dependencies/$LZ4_FILE" ] || wget --no-clobber --quiet --output-document="dependencies/$LZ4_FILE" "$LZ4_URI" | true
[ -f "dependencies/$RECTPACK2D_FILE" ] || wget --no-clobber --quiet --output-document="dependencies/$RECTPACK2D_FILE" "$RECTPACK2D_URI" | true
[ -f "dependencies/$RMLUI_FILE" ] || wget --no-clobber --quiet --output-document="dependencies/$RMLUI_FILE" "$RMLUI_URI" | true

if [ -x dos2unix ] && [ -x md5sum ]; then
  dos2unix --quiet "dependencies/dependencies.md5"
  md5sum --quiet "dependencies/dependencies.md5"

  if [ "$?" != 0]; then
    echo "Failed md5 checksum verification"
    exit 1
  fi
fi
