/* Copyright (c) 2023 M.A.X. Port Team
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#define LOCALIZATION_INI_MAP                                                                                           \
    {"language", INI_SECTION}, {"acbe", INI_STRING}, {"b9d9", INI_STRING}, {"cdcc", INI_STRING}, {"07d7", INI_STRING}, \
        {"d25b", INI_STRING}, {"cfb8", INI_STRING}, {"b441", INI_STRING}, {"ff10", INI_STRING}, {"0aea", INI_STRING},  \
        {"ed57", INI_STRING}, {"0a4b", INI_STRING}, {"5fd6", INI_STRING}, {"0579", INI_STRING}, {"7516", INI_STRING},  \
        {"d139", INI_STRING}, {"57f8", INI_STRING}, {"9665", INI_STRING}, {"87e8", INI_STRING}, {"61e6", INI_STRING},  \
        {"ac9d", INI_STRING}, {"5f9a", INI_STRING}, {"5f24", INI_STRING}, {"b8fe", INI_STRING}, {"2ff7", INI_STRING},  \
        {"9c91", INI_STRING}, {"2162", INI_STRING}, {"24d7", INI_STRING}, {"f814", INI_STRING}, {"73f7", INI_STRING},  \
        {"2acf", INI_STRING}, {"19b2", INI_STRING}, {"f260", INI_STRING}, {"7a37", INI_STRING}, {"b215", INI_STRING},  \
        {"961d", INI_STRING}, {"3226", INI_STRING}, {"61fa", INI_STRING}, {"3d58", INI_STRING}, {"1dfe", INI_STRING},  \
        {"f957", INI_STRING}, {"17c7", INI_STRING}, {"1226", INI_STRING}, {"2ab8", INI_STRING}, {"ba19", INI_STRING},  \
        {"d486", INI_STRING}, {"ec7d", INI_STRING}, {"0d5a", INI_STRING}, {"11a6", INI_STRING}, {"1976", INI_STRING},  \
        {"6b67", INI_STRING}, {"68dc", INI_STRING}, {"8433", INI_STRING}, {"62fa", INI_STRING}, {"3a76", INI_STRING},  \
        {"526e", INI_STRING}, {"53cf", INI_STRING}, {"204a", INI_STRING}, {"c529", INI_STRING}, {"06cb", INI_STRING},  \
        {"6682", INI_STRING}, {"e2d0", INI_STRING}, {"bdd2", INI_STRING}, {"faaf", INI_STRING}, {"207f", INI_STRING},  \
        {"2180", INI_STRING}, {"064b", INI_STRING}, {"b6b7", INI_STRING}, {"1031", INI_STRING}, {"05fa", INI_STRING},  \
        {"ff73", INI_STRING}, {"fa62", INI_STRING}, {"9eb5", INI_STRING}, {"01fa", INI_STRING}, {"c4e7", INI_STRING},  \
        {"803c", INI_STRING}, {"3346", INI_STRING}, {"f6f4", INI_STRING}, {"0de3", INI_STRING}, {"bd89", INI_STRING},  \
        {"c6aa", INI_STRING}, {"0b85", INI_STRING}, {"7a2c", INI_STRING}, {"f199", INI_STRING}, {"fb18", INI_STRING},  \
        {"64fd", INI_STRING}, {"ed1b", INI_STRING}, {"2683", INI_STRING}, {"0dfd", INI_STRING}, {"b0e8", INI_STRING},  \
        {"4d73", INI_STRING}, {"64e3", INI_STRING}, {"834a", INI_STRING}, {"e02a", INI_STRING}, {"e674", INI_STRING},  \
        {"056f", INI_STRING}, {"5fa1", INI_STRING}, {"eb71", INI_STRING}, {"57a6", INI_STRING}, {"ab7e", INI_STRING},  \
        {"3201", INI_STRING}, {"fc09", INI_STRING}, {"2443", INI_STRING}, {"bdc0", INI_STRING}, {"1196", INI_STRING},  \
        {"7ec0", INI_STRING}, {"f0dc", INI_STRING}, {"c163", INI_STRING}, {"8688", INI_STRING}, {"0fbe", INI_STRING},  \
        {"27af", INI_STRING}, {"e609", INI_STRING}, {"670f", INI_STRING}, {"003c", INI_STRING}, {"c46e", INI_STRING},  \
        {"eeb4", INI_STRING}, {"a1f0", INI_STRING}, {"755b", INI_STRING}, {"e3a4", INI_STRING}, {"d7d0", INI_STRING},  \
        {"2ec0", INI_STRING}, {"7c23", INI_STRING}, {"71f1", INI_STRING}, {"77de", INI_STRING}, {"bb4a", INI_STRING},  \
        {"fc74", INI_STRING}, {"7564", INI_STRING}, {"c9c5", INI_STRING}, {"7b17", INI_STRING}, {"51e1", INI_STRING},  \
        {"3d2c", INI_STRING}, {"5c73", INI_STRING}, {"1b9b", INI_STRING}, {"6249", INI_STRING}, {"5653", INI_STRING},  \
        {"4556", INI_STRING}, {"153d", INI_STRING}, {"6b25", INI_STRING}, {"aaea", INI_STRING}, {"bb8a", INI_STRING},  \
        {"cdd0", INI_STRING}, {"ccca", INI_STRING}, {"1347", INI_STRING}, {"c164", INI_STRING}, {"c116", INI_STRING},  \
        {"9edb", INI_STRING}, {"6bc6", INI_STRING}, {"5ced", INI_STRING}, {"3b69", INI_STRING}, {"c499", INI_STRING},  \
        {"4afd", INI_STRING}, {"bc1c", INI_STRING}, {"908e", INI_STRING}, {"b2b3", INI_STRING}, {"00a7", INI_STRING},  \
        {"eb11", INI_STRING}, {"3004", INI_STRING}, {"07f8", INI_STRING}, {"aeb0", INI_STRING}, {"773a", INI_STRING},  \
        {"af4a", INI_STRING}, {"cdf8", INI_STRING}, {"ee24", INI_STRING}, {"bda4", INI_STRING}, {"e3ee", INI_STRING},  \
        {"0a07", INI_STRING}, {"a8bd", INI_STRING}, {"e3cd", INI_STRING}, {"2cd0", INI_STRING}, {"9753", INI_STRING},  \
        {"9733", INI_STRING}, {"fd20", INI_STRING}, {"73cc", INI_STRING}, {"3206", INI_STRING}, {"20c3", INI_STRING},  \
        {"f900", INI_STRING}, {"eb6c", INI_STRING}, {"c719", INI_STRING}, {"dcc6", INI_STRING}, {"e285", INI_STRING},  \
        {"470e", INI_STRING}, {"f640", INI_STRING}, {"f47b", INI_STRING}, {"abd7", INI_STRING}, {"10eb", INI_STRING},  \
        {"7615", INI_STRING}, {"d2f1", INI_STRING}, {"5504", INI_STRING}, {"ecbd", INI_STRING}, {"d984", INI_STRING},  \
        {"930a", INI_STRING}, {"1fd7", INI_STRING}, {"7c90", INI_STRING}, {"c65e", INI_STRING}, {"5ae3", INI_STRING},  \
        {"42b7", INI_STRING}, {"ea89", INI_STRING}, {"311d", INI_STRING}, {"9880", INI_STRING}, {"f37a", INI_STRING},  \
        {"3e56", INI_STRING}, {"9897", INI_STRING}, {"df78", INI_STRING}, {"851c", INI_STRING}, {"3a97", INI_STRING},  \
        {"5cb4", INI_STRING}, {"dfe1", INI_STRING}, {"c2eb", INI_STRING}, {"df36", INI_STRING}, {"263f", INI_STRING},  \
        {"0d6b", INI_STRING}, {"758a", INI_STRING}, {"c977", INI_STRING}, {"ea0b", INI_STRING}, {"b38a", INI_STRING},  \
        {"abcf", INI_STRING}, {"13d9", INI_STRING}, {"1d69", INI_STRING}, {"848e", INI_STRING}, {"8d59", INI_STRING},  \
        {"c9b3", INI_STRING}, {"d4ca", INI_STRING}, {"81c5", INI_STRING}, {"1e1a", INI_STRING}, {"3aea", INI_STRING},  \
        {"c6fe", INI_STRING}, {"7be8", INI_STRING}, {"160c", INI_STRING}, {"c54a", INI_STRING}, {"5f25", INI_STRING},  \
        {"54ba", INI_STRING}, {"45e4", INI_STRING}, {"2a38", INI_STRING}, {"c35e", INI_STRING}, {"bd3a", INI_STRING},  \
        {"361e", INI_STRING}, {"c02c", INI_STRING}, {"5027", INI_STRING}, {"1274", INI_STRING}, {"c372", INI_STRING},  \
        {"2bce", INI_STRING}, {"d28b", INI_STRING}, {"a9fd", INI_STRING}, {"abc7", INI_STRING}, {"6696", INI_STRING},  \
        {"7391", INI_STRING}, {"e2e9", INI_STRING}, {"1ff5", INI_STRING}, {"dacc", INI_STRING}, {"460b", INI_STRING},  \
        {"211b", INI_STRING}, {"920e", INI_STRING}, {"88c4", INI_STRING}, {"5995", INI_STRING}, {"7429", INI_STRING},  \
        {"5de7", INI_STRING}, {"ea1c", INI_STRING}, {"0d7d", INI_STRING}, {"c3b2", INI_STRING}, {"6af6", INI_STRING},  \
        {"ea1a", INI_STRING}, {"cdbf", INI_STRING}, {"1f51", INI_STRING}, {"e96b", INI_STRING}, {"8dac", INI_STRING},  \
        {"1d99", INI_STRING}, {"87c5", INI_STRING}, {"0010", INI_STRING}, {"2200", INI_STRING}, {"feff", INI_STRING},  \
        {"2c8d", INI_STRING}, {"ce0f", INI_STRING}, {"dfe7", INI_STRING}, {"0664", INI_STRING}, {"5ece", INI_STRING},  \
        {"68b7", INI_STRING}, {"6553", INI_STRING}, {"dc38", INI_STRING}, {"ab01", INI_STRING}, {"e2c5", INI_STRING},  \
        {"1469", INI_STRING}, {"a4b3", INI_STRING}, {"5e16", INI_STRING}, {"6172", INI_STRING}, {"7bcd", INI_STRING},  \
        {"5f83", INI_STRING}, {"8115", INI_STRING}, {"e843", INI_STRING}, {"7508", INI_STRING}, {"d80d", INI_STRING},  \
        {"85f8", INI_STRING}, {"1925", INI_STRING}, {"bc06", INI_STRING}, {"c331", INI_STRING}, {"1200", INI_STRING},  \
        {"74d3", INI_STRING}, {"8c62", INI_STRING}, {"276c", INI_STRING}, {"d82e", INI_STRING}, {"01d0", INI_STRING},  \
        {"c64e", INI_STRING}, {"8d3e", INI_STRING}, {"9df3", INI_STRING}, {"5e9c", INI_STRING}, {"6fe5", INI_STRING},  \
        {"2488", INI_STRING}, {"a2a6", INI_STRING}, {"7ccc", INI_STRING}, {"1f7a", INI_STRING}, {"f0d6", INI_STRING},  \
        {"4bfa", INI_STRING}, {"ceb6", INI_STRING}, {"f3e3", INI_STRING}, {"db0c", INI_STRING}, {"7f53", INI_STRING},  \
        {"6976", INI_STRING}, {"62f5", INI_STRING}, {"d81e", INI_STRING}, {"fca3", INI_STRING}, {"4027", INI_STRING},  \
        {"bbcc", INI_STRING}, {"2269", INI_STRING}, {"206c", INI_STRING}, {"59ad", INI_STRING}, {"49a2", INI_STRING},  \
        {"24d8", INI_STRING}, {"4a91", INI_STRING}, {"e9d8", INI_STRING}, {"4790", INI_STRING}, {"1867", INI_STRING},  \
        {"ec05", INI_STRING}, {"e946", INI_STRING}, {"cb78", INI_STRING}, {"5512", INI_STRING}, {"55c8", INI_STRING},  \
        {"bc94", INI_STRING}, {"06ec", INI_STRING}, {"f2b3", INI_STRING}, {"9b46", INI_STRING}, {"5d49", INI_STRING},  \
        {"385b", INI_STRING}, {"f27a", INI_STRING}, {"04b5", INI_STRING}, {"35f9", INI_STRING}, {"0cb7", INI_STRING},  \
        {"a661", INI_STRING}, {"b764", INI_STRING}, {"6c04", INI_STRING}, {"c56b", INI_STRING}, {"1c1d", INI_STRING},  \
        {"3d0b", INI_STRING}, {"ec45", INI_STRING}, {"af71", INI_STRING}, {"fc1c", INI_STRING}, {"1c7d", INI_STRING},  \
        {"d895", INI_STRING}, {"85cd", INI_STRING}, {"d46a", INI_STRING}, {"dd95", INI_STRING}, {"961e", INI_STRING},  \
        {"97c6", INI_STRING}, {"e878", INI_STRING}, {"6637", INI_STRING}, {"cdfc", INI_STRING}, {"4ba6", INI_STRING},  \
        {"90a9", INI_STRING}, {"28f9", INI_STRING}, {"dc41", INI_STRING}, {"8339", INI_STRING}, {"7013", INI_STRING},  \
        {"b605", INI_STRING}, {"2a6b", INI_STRING}, {"d17d", INI_STRING}, {"182b", INI_STRING}, {"02c9", INI_STRING},  \
        {"3d29", INI_STRING}, {"884f", INI_STRING}, {"878a", INI_STRING}, {"3838", INI_STRING}, {"7eec", INI_STRING},  \
        {"c7a9", INI_STRING}, {"7064", INI_STRING}, {"f731", INI_STRING}, {"bf00", INI_STRING}, {"847e", INI_STRING},  \
        {"e13e", INI_STRING}, {"0a6f", INI_STRING}, {"a980", INI_STRING}, {"095f", INI_STRING}, {"f482", INI_STRING},  \
        {"80f9", INI_STRING}, {"8bc0", INI_STRING}, {"c663", INI_STRING}, {"befb", INI_STRING}, {"662e", INI_STRING},  \
        {"41cd", INI_STRING}, {"7891", INI_STRING}, {"c82a", INI_STRING}, {"68e0", INI_STRING}, {"2519", INI_STRING},  \
        {"8850", INI_STRING}, {"9ad1", INI_STRING}, {"0fd1", INI_STRING}, {"fe3d", INI_STRING}, {"936a", INI_STRING},  \
        {"1331", INI_STRING}, {"e06f", INI_STRING}, {"919b", INI_STRING}, {"c35a", INI_STRING}, {"0674", INI_STRING},  \
        {"498a", INI_STRING}, {"6fbd", INI_STRING}, {"364b", INI_STRING}, {"a8a5", INI_STRING}, {"0853", INI_STRING},  \
        {"09fb", INI_STRING}, {"51c9", INI_STRING}, {"9dc7", INI_STRING}, {"f6a7", INI_STRING}, {"abc4", INI_STRING},  \
        {"0ae1", INI_STRING}, {"8ead", INI_STRING}, {"fab6", INI_STRING}, {"1795", INI_STRING}, {"b291", INI_STRING},  \
        {"31f7", INI_STRING}, {"b23a", INI_STRING}, {"f0f9", INI_STRING}, {"d040", INI_STRING}, {"9964", INI_STRING},  \
        {"177b", INI_STRING}, {"67e6", INI_STRING}, {"c5af", INI_STRING}, {"9376", INI_STRING}, {"387d", INI_STRING},  \
        {"99e0", INI_STRING}, {"12f1", INI_STRING}, {"85c8", INI_STRING}, {"f813", INI_STRING}, {"11ae", INI_STRING},  \
        {"06d1", INI_STRING}, {"b2a8", INI_STRING}, {"7a22", INI_STRING}, {"efb3", INI_STRING}, {"fda7", INI_STRING},  \
        {"ab0a", INI_STRING}, {"163c", INI_STRING}, {"3ce2", INI_STRING}, {"d126", INI_STRING}, {"00a5", INI_STRING},  \
        {"7bd6", INI_STRING}, {"1471", INI_STRING}, {"c336", INI_STRING}, {"f40f", INI_STRING}, {"6c6c", INI_STRING},  \
        {"8d9a", INI_STRING}, {"cb1d", INI_STRING}, {"5195", INI_STRING}, {"012c", INI_STRING}, {"323e", INI_STRING},  \
        {"2385", INI_STRING}, {"6f14", INI_STRING}, {"708f", INI_STRING}, {"6903", INI_STRING}, {"4d80", INI_STRING},  \
        {"ae4e", INI_STRING}, {"d0a4", INI_STRING}, {"fdd7", INI_STRING}, {"0ac0", INI_STRING}, {"5f4b", INI_STRING},  \
        {"8475", INI_STRING}, {"cffe", INI_STRING}, {"7842", INI_STRING}, {"da7e", INI_STRING}, {"6517", INI_STRING},  \
        {"e43b", INI_STRING}, {"f588", INI_STRING}, {"c78b", INI_STRING}, {"895d", INI_STRING}, {"5f5f", INI_STRING},  \
        {"e7b2", INI_STRING}, {"f3fe", INI_STRING}, {"8524", INI_STRING}, {"4bb8", INI_STRING}, {"f408", INI_STRING},  \
        {"0935", INI_STRING}, {"7303", INI_STRING}, {"94ef", INI_STRING}, {"c46c", INI_STRING}, {"48ac", INI_STRING},  \
        {"275a", INI_STRING}, {"ea47", INI_STRING}, {"fcf0", INI_STRING}, {"6426", INI_STRING}, {"7ea8", INI_STRING},  \
        {"386d", INI_STRING}, {"41e5", INI_STRING}, {"bbcb", INI_STRING}, {"ba99", INI_STRING}, {"f7c8", INI_STRING},  \
        {"67bc", INI_STRING}, {"9d35", INI_STRING}, {"8a8d", INI_STRING}, {"bf2c", INI_STRING}, {"897f", INI_STRING},  \
        {"7e91", INI_STRING}, {"f5ee", INI_STRING}, {"eb1b", INI_STRING}, {"aff0", INI_STRING}, {"5985", INI_STRING},  \
        {"9ffa", INI_STRING}, {"76ed", INI_STRING}, {"dc93", INI_STRING}, {"bda5", INI_STRING}, {"4042", INI_STRING},  \
        {"9605", INI_STRING}, {"ef0a", INI_STRING}, {"4869", INI_STRING}, {"5939", INI_STRING}, {"119e", INI_STRING},  \
        {"8a6b", INI_STRING}, {"72fa", INI_STRING}, {"1baf", INI_STRING}, {"d0db", INI_STRING}, {"808a", INI_STRING},  \
        {"0b5a", INI_STRING}, {"5fa7", INI_STRING}, {"e4bb", INI_STRING}, {"a80a", INI_STRING}, {"8610", INI_STRING},  \
        {"da62", INI_STRING}, {"8448", INI_STRING}, {"de1b", INI_STRING}, {"e96a", INI_STRING}, {"4599", INI_STRING},  \
        {"1d15", INI_STRING}, {"e1e4", INI_STRING}, {"3b7b", INI_STRING}, {"fde2", INI_STRING}, {"e644", INI_STRING},  \
        {"2d88", INI_STRING}, {"8b31", INI_STRING}, {"a2bb", INI_STRING}, {"9c54", INI_STRING}, {"779f", INI_STRING},  \
        {"99b8", INI_STRING}, {"366c", INI_STRING}, {"03d2", INI_STRING}, {"8f89", INI_STRING}, {"218f", INI_STRING},  \
        {"f7e4", INI_STRING}, {"0ba9", INI_STRING}, {"dbc7", INI_STRING}, {"f793", INI_STRING}, {"e512", INI_STRING},  \
        {"a724", INI_STRING}, {"c4eb", INI_STRING}, {"3ade", INI_STRING}, {"d558", INI_STRING}, {"10c4", INI_STRING},  \
        {"4ef9", INI_STRING}, {"48bd", INI_STRING}, {"94df", INI_STRING}, {"8e58", INI_STRING}, {"dca9", INI_STRING},  \
        {"8c28", INI_STRING}, {"ccfe", INI_STRING}, {"eac9", INI_STRING}, {"ec35", INI_STRING}, {"9c1d", INI_STRING},  \
        {"0c4a", INI_STRING}, {"2484", INI_STRING}, {"291d", INI_STRING}, {"3099", INI_STRING}, {"298d", INI_STRING},  \
        {"9689", INI_STRING}, {"f5d6", INI_STRING}, {"9427", INI_STRING}, {"d1d8", INI_STRING}, {"76b7", INI_STRING},  \
        {"b459", INI_STRING}, {"4065", INI_STRING}, {"a07a", INI_STRING}, {"7015", INI_STRING}, {"639d", INI_STRING},  \
        {"da8e", INI_STRING}, {"f0a3", INI_STRING}, {"1dc3", INI_STRING}, {"eb1c", INI_STRING}, {"0e00", INI_STRING},  \
        {"2de0", INI_STRING}, {"e22c", INI_STRING}, {"7cb8", INI_STRING}, {"ae0b", INI_STRING}, {"f9bb", INI_STRING},  \
        {"755f", INI_STRING}, {"2879", INI_STRING}, {"6b98", INI_STRING}, {"b3eb", INI_STRING}, {"00d3", INI_STRING},  \
        {"7c8d", INI_STRING}, {"6907", INI_STRING}, {"3fda", INI_STRING}, {"f70f", INI_STRING}, {"ba25", INI_STRING},  \
        {"b2c7", INI_STRING}, {"644b", INI_STRING}, {"6eb0", INI_STRING}, {"c2e5", INI_STRING}, {"adf0", INI_STRING},  \
        {"2eeb", INI_STRING}, {"87bf", INI_STRING}, {"e9db", INI_STRING}, {"64fb", INI_STRING}, {"5940", INI_STRING},  \
        {"f11f", INI_STRING}, {"238c", INI_STRING}, {"bf3b", INI_STRING}, {"2349", INI_STRING}, {"09e9", INI_STRING},  \
        {"f99e", INI_STRING}, {"c8b2", INI_STRING}, {"24e6", INI_STRING}, {"86df", INI_STRING}, {"de3f", INI_STRING},  \
        {"f019", INI_STRING}, {"d5b2", INI_STRING}, {"e791", INI_STRING}, {"d5fa", INI_STRING}, {"6a65", INI_STRING},  \
        {"3bda", INI_STRING}, {"3bb7", INI_STRING}, {"11a8", INI_STRING}, {"75a0", INI_STRING}, {"d0a7", INI_STRING},  \
        {"ee25", INI_STRING}, {"a24d", INI_STRING}, {"37b7", INI_STRING}, {"bb85", INI_STRING}, {"b663", INI_STRING},  \
        {"ab89", INI_STRING}, {"c7e3", INI_STRING}, {"b542", INI_STRING}, {"c303", INI_STRING}, {"8332", INI_STRING},  \
        {"e0f9", INI_STRING}, {"ef35", INI_STRING}, {"7be4", INI_STRING}, {"62a6", INI_STRING}, {"9a28", INI_STRING},  \
        {"3129", INI_STRING}, {"2abe", INI_STRING}, {"87d7", INI_STRING}, {"1dc1", INI_STRING}, {"275c", INI_STRING},  \
        {"6da5", INI_STRING}, {"f394", INI_STRING}, {"a8a6", INI_STRING}, {"a3ee", INI_STRING}, {"319d", INI_STRING},  \
        {"76a7", INI_STRING}, {"deb1", INI_STRING}, {"bda3", INI_STRING}, {"f047", INI_STRING}, {"b719", INI_STRING},  \
        {"3b4a", INI_STRING}, {"1439", INI_STRING}, {"7697", INI_STRING}, {"efc4", INI_STRING}, {"d94e", INI_STRING},  \
        {"c394", INI_STRING}, {"a4e4", INI_STRING}, {"891f", INI_STRING}, {"3347", INI_STRING}, {"199c", INI_STRING},  \
        {"50c9", INI_STRING}, {"27e1", INI_STRING}, {"4bde", INI_STRING}, {"9fb6", INI_STRING}, {"8787", INI_STRING},  \
        {"38e5", INI_STRING}, {"04d7", INI_STRING}, {"bbb4", INI_STRING}, {"2ecc", INI_STRING}, {"4a3b", INI_STRING},  \
        {"1c43", INI_STRING}, {"4393", INI_STRING}, {"28d5", INI_STRING}, {"929b", INI_STRING}, {"1f97", INI_STRING},  \
        {"045b", INI_STRING}, {"e5ae", INI_STRING}, {"64cf", INI_STRING}, {"138d", INI_STRING}, {"abea", INI_STRING},  \
        {"4262", INI_STRING}, {"0334", INI_STRING}, {"3baf", INI_STRING}, {"13b0", INI_STRING}, {"a18e", INI_STRING},  \
        {"f3cd", INI_STRING}, {"2b0e", INI_STRING}, {"7e3b", INI_STRING}, {"3609", INI_STRING}, {"d181", INI_STRING},  \
        {"e228", INI_STRING}, {"9892", INI_STRING}, {"74d9", INI_STRING}, {"0bd5", INI_STRING}, {"4cd5", INI_STRING},  \
        {"7382", INI_STRING}, {"86bc", INI_STRING}, {"a592", INI_STRING}, {"07f9", INI_STRING}, {"5857", INI_STRING},  \
        {"920c", INI_STRING}, {"dbae", INI_STRING}, {"df4f", INI_STRING}, {"5426", INI_STRING}, {"63e7", INI_STRING},  \
        {"f846", INI_STRING}, {"278f", INI_STRING}, {"6b01", INI_STRING}, {"f752", INI_STRING}, {"d4ac", INI_STRING},  \
        {"1509", INI_STRING}, {"1fc6", INI_STRING}, {"2fcb", INI_STRING}, {"61ef", INI_STRING}, {"a03c", INI_STRING},  \
        {"1ec8", INI_STRING}, {"357f", INI_STRING}, {"be30", INI_STRING}, {"6e67", INI_STRING}, {"de7c", INI_STRING},  \
        {"6e4e", INI_STRING}, {"768e", INI_STRING}, {"5f44", INI_STRING}, {"1e2d", INI_STRING}, {"38df", INI_STRING},  \
        {"dd4a", INI_STRING}, {"e7f7", INI_STRING}, {"a7ec", INI_STRING}, {"979d", INI_STRING}, {"244f", INI_STRING},  \
        {"5006", INI_STRING}, {"8974", INI_STRING}, {"1b58", INI_STRING}, {"e302", INI_STRING}, {"b452", INI_STRING},  \
        {"abbf", INI_STRING}, {"e356", INI_STRING}, {"54fa", INI_STRING}, {"f88f", INI_STRING}, {"353a", INI_STRING},  \
        {"b7dd", INI_STRING}, {"adcf", INI_STRING}, {"f4d5", INI_STRING}, {"ab3a", INI_STRING}, {"625d", INI_STRING},  \
        {"513e", INI_STRING}, {"7e10", INI_STRING}, {"4be1", INI_STRING}, {"803e", INI_STRING}, {"5eec", INI_STRING},  \
        {"da78", INI_STRING}, {"54eb", INI_STRING}, {"563d", INI_STRING}, {"78f1", INI_STRING}, {"db51", INI_STRING},  \
        {"c13a", INI_STRING}, {"00b7", INI_STRING}, {"963a", INI_STRING}, {"c14a", INI_STRING}, {"ecc9", INI_STRING},  \
        {"9d98", INI_STRING}, {"d033", INI_STRING}, {"494c", INI_STRING}, {"8b45", INI_STRING}, {"2682", INI_STRING},  \
        {"4bf8", INI_STRING}, {"dea8", INI_STRING}, {"8a2c", INI_STRING}, {"1a03", INI_STRING}, {"7198", INI_STRING},  \
        {"2954", INI_STRING}, {"3bc3", INI_STRING}, {"98a8", INI_STRING}, {"5e40", INI_STRING}, {"2540", INI_STRING},  \
        {"d510", INI_STRING}, {"054b", INI_STRING}, {"527f", INI_STRING}, {"3641", INI_STRING}, {"9e61", INI_STRING},  \
        {"49d1", INI_STRING}, {"be42", INI_STRING}, {"d10e", INI_STRING}, {"6136", INI_STRING}, {"7dfb", INI_STRING},  \
        {"cf39", INI_STRING}, {"94b7", INI_STRING}, {"592f", INI_STRING}, {"eb74", INI_STRING}, {"40c7", INI_STRING},  \
        {"c771", INI_STRING}, {"8481", INI_STRING}, {"1e19", INI_STRING}, {"5ae6", INI_STRING}, {"a80f", INI_STRING},  \
        {"5432", INI_STRING}, {"04dd", INI_STRING}, {"dff1", INI_STRING}, {"e187", INI_STRING}, {"89a3", INI_STRING},  \
        {"660b", INI_STRING}, {"d6a7", INI_STRING}, {"e3e0", INI_STRING}, {"d23e", INI_STRING}, {"e6d7", INI_STRING},  \
        {"2962", INI_STRING}, {"01c2", INI_STRING}, {"9ed6", INI_STRING}, {"08ad", INI_STRING}, {"79a5", INI_STRING},  \
        {"1a05", INI_STRING}, {"1522", INI_STRING}, {"1c9b", INI_STRING}, {"7ed6", INI_STRING}, {"fbcd", INI_STRING},  \
        {"7084", INI_STRING}, {"bbf4", INI_STRING}, {"5a81", INI_STRING}, {"c8d3", INI_STRING}, {"10c9", INI_STRING},  \
        {"4582", INI_STRING}, {"5a91", INI_STRING}, {"5ea2", INI_STRING}, {"a5d2", INI_STRING}, {"3184", INI_STRING},  \
        {"524f", INI_STRING}, {"656d", INI_STRING}, {"53b3", INI_STRING}, {"5053", INI_STRING}, {"c2d8", INI_STRING},  \
        {"e1a5", INI_STRING}, {"75d4", INI_STRING}, {"51d9", INI_STRING}, {"93dc", INI_STRING}, {"760c", INI_STRING},  \
        {"8672", INI_STRING}, {"4340", INI_STRING}, {"282f", INI_STRING}, {"731e", INI_STRING}, {"a135", INI_STRING},  \
        {"e8a8", INI_STRING}, {"f830", INI_STRING}, {"42ec", INI_STRING}, {"43a4", INI_STRING}, {"66ad", INI_STRING},  \
        {"1c3b", INI_STRING}, {"5d61", INI_STRING}, {"49c1", INI_STRING}, {"c971", INI_STRING}, {"9736", INI_STRING},  \
        {"c3d2", INI_STRING}, {"8f0d", INI_STRING}, {"4d4a", INI_STRING}, {"02e7", INI_STRING}, {"a22e", INI_STRING},  \
        {"2627", INI_STRING}, {"b393", INI_STRING}, {"be71", INI_STRING}, {"29b9", INI_STRING}, {"c323", INI_STRING},  \
        {"bc7b", INI_STRING}, {"381d", INI_STRING}, {"0c63", INI_STRING}, {"27ca", INI_STRING}, {"eebb", INI_STRING},  \
        {"70ae", INI_STRING}, {"e9d2", INI_STRING}, {"43e4", INI_STRING}, {"ca88", INI_STRING}, {"784f", INI_STRING},  \
        {"331b", INI_STRING}, {"751e", INI_STRING}, {"73ae", INI_STRING}, {"c2e2", INI_STRING}, {"97e9", INI_STRING},  \
        {"fa10", INI_STRING}, {"e103", INI_STRING}, {"e531", INI_STRING}, {"6182", INI_STRING}, {"4b34", INI_STRING},  \
        {"5972", INI_STRING}, {"6006", INI_STRING}, {"79b5", INI_STRING}, {"c11b", INI_STRING}, {"aaad", INI_STRING},  \
        {"30c9", INI_STRING}, {"75fb", INI_STRING}, {"cbf4", INI_STRING}, {"9a30", INI_STRING}, {"0fc3", INI_STRING},  \
        {"6fae", INI_STRING}, {"5cd9", INI_STRING}, {"e1c0", INI_STRING}, {"5282", INI_STRING}, {"4cb4", INI_STRING},  \
        {"3764", INI_STRING}, {"96b3", INI_STRING}, {"6689", INI_STRING}, {"64b7", INI_STRING}, {"d8d2", INI_STRING},  \
        {"24cb", INI_STRING}, {"f5c8", INI_STRING}, {"c75e", INI_STRING}, {"703f", INI_STRING}, {"65a8", INI_STRING},  \
        {"0886", INI_STRING}, {"d982", INI_STRING}, {"3892", INI_STRING}, {"5a0e", INI_STRING}, {"0777", INI_STRING},  \
        {"b41b", INI_STRING}, {"72a5", INI_STRING}, {"3b31", INI_STRING}, {"ee79", INI_STRING}, {"a2c3", INI_STRING},  \
        {"470d", INI_STRING}, {"e7f8", INI_STRING}, {"a309", INI_STRING}, {"b66a", INI_STRING}, {"603b", INI_STRING},  \
        {"4ef8", INI_STRING}, {"aafe", INI_STRING}, {"d28e", INI_STRING}, {"3b10", INI_STRING}, {"7a39", INI_STRING},  \
        {"1ccb", INI_STRING}, {"b2bb", INI_STRING}, {"95a3", INI_STRING}, {"8a1d", INI_STRING}, {"809e", INI_STRING},  \
        {"d58b", INI_STRING}, {"ca60", INI_STRING}, {"c0b2", INI_STRING}, {"3a41", INI_STRING}, {"301e", INI_STRING},  \
        {"baf1", INI_STRING}, {"03cb", INI_STRING}, {"a685", INI_STRING}, {"dcf4", INI_STRING}, {"0aa6", INI_STRING},  \
        {"c263", INI_STRING}, {"3fa5", INI_STRING}, {"051d", INI_STRING}, {"b6ef", INI_STRING}, {"a3da", INI_STRING},  \
        {"45c2", INI_STRING}, {"d26f", INI_STRING}, {"c838", INI_STRING}, {"d2c2", INI_STRING}, {"f3a3", INI_STRING},  \
        {"8def", INI_STRING}, {"5bc4", INI_STRING}, {"2643", INI_STRING}, {"e812", INI_STRING}, {"71d4", INI_STRING},  \
        {"d932", INI_STRING}, {"c597", INI_STRING}, {"9dff", INI_STRING}, {"65cf", INI_STRING}, {"23bb", INI_STRING},  \
        {"e4c1", INI_STRING}, {"3fec", INI_STRING}, {"52b5", INI_STRING}, {"373a", INI_STRING}, {"d933", INI_STRING},  \
        {"3876", INI_STRING}, {"5be1", INI_STRING}, {"fac3", INI_STRING}, {"8fdf", INI_STRING}, {"156b", INI_STRING},  \
        {"f152", INI_STRING}, {"f5be", INI_STRING}, {"7dd4", INI_STRING}, {"3753", INI_STRING}, {"a28a", INI_STRING},  \
        {"93e1", INI_STRING}, {"66e9", INI_STRING}, {"cc81", INI_STRING}, {"6b15", INI_STRING}, {"ba90", INI_STRING},  \
        {"9e7c", INI_STRING}, {"ad96", INI_STRING}, {"461c", INI_STRING}, {"365d", INI_STRING}, {"363b", INI_STRING},  \
        {"4cc2", INI_STRING}, {"916e", INI_STRING}, {"eb92", INI_STRING}, {"0f0c", INI_STRING}, {"fe06", INI_STRING},  \
        {"4ae7", INI_STRING}, {"9cbf", INI_STRING}, {"06b2", INI_STRING}, {"358f", INI_STRING}, {"5662", INI_STRING},  \
        {"f368", INI_STRING}, {"fb02", INI_STRING}, {"2b1a", INI_STRING}, {"ac8d", INI_STRING}, {"76ab", INI_STRING},  \
        {"ee2f", INI_STRING}, {"24e7", INI_STRING}, {"f511", INI_STRING}, {"efbe", INI_STRING}, {"2a9f", INI_STRING},  \
        {"a04b", INI_STRING}, {"48bb", INI_STRING}, {"71d6", INI_STRING}, {"c8fd", INI_STRING}, {"fe5b", INI_STRING},  \
        {"2e66", INI_STRING}, {"a8d9", INI_STRING}, {"62eb", INI_STRING}, {"60d7", INI_STRING}, {"883c", INI_STRING},  \
        {"4195", INI_STRING}, {"9b5d", INI_STRING}, {"4044", INI_STRING}, {"d91c", INI_STRING}, {"9f7c", INI_STRING},  \
        {"48c0", INI_STRING}, {"1801", INI_STRING}, {"91b3", INI_STRING}, {"1cff", INI_STRING}, {"b952", INI_STRING},  \
        {"0a15", INI_STRING}, {"bde7", INI_STRING}, {"0ca9", INI_STRING}, {"0f27", INI_STRING}, {"a44c", INI_STRING},  \
        {"1d38", INI_STRING}, {"a0ee", INI_STRING}, {"8967", INI_STRING}, {"2693", INI_STRING}, {"d5cb", INI_STRING},  \
        {"ef77", INI_STRING}, {"b0b9", INI_STRING}, {"886b", INI_STRING}, {"e08d", INI_STRING}, {"6c45", INI_STRING},  \
        {"7fef", INI_STRING}, {"97a2", INI_STRING}, {"0cf6", INI_STRING}, {"524e", INI_STRING}, {"2b7d", INI_STRING},  \
        {"7e56", INI_STRING}, {"0286", INI_STRING}, {"e183", INI_STRING}, {"9d39", INI_STRING}, {"78a0", INI_STRING},  \
        {"63d6", INI_STRING}, {"81df", INI_STRING}, {"bfe6", INI_STRING}, {"a1a1", INI_STRING}, {"bf85", INI_STRING},  \
        {"b3ef", INI_STRING}, {"c710", INI_STRING}, {"87e9", INI_STRING}, {"7b6d", INI_STRING}, {"cced", INI_STRING},  \
        {"bcf7", INI_STRING}, {"8576", INI_STRING}, {"b8d3", INI_STRING}, {"d599", INI_STRING}, {"b4dc", INI_STRING},  \
        {"6d6a", INI_STRING}, {"a0fd", INI_STRING}, {"5f6b", INI_STRING}, {"2e00", INI_STRING}, {"6889", INI_STRING},  \
        {"283e", INI_STRING}, {"53c3", INI_STRING}, {"3f13", INI_STRING}, {"1da0", INI_STRING}, {"bd97", INI_STRING},  \
        {"cec1", INI_STRING}, {"200c", INI_STRING}, {"8452", INI_STRING}, {"98c9", INI_STRING}, {"33b7", INI_STRING},  \
        {"d9c8", INI_STRING}, {"df26", INI_STRING}, {"5fe9", INI_STRING}, {"e7b6", INI_STRING}, {"7a07", INI_STRING},  \
        {"a615", INI_STRING}, {"b9b7", INI_STRING}, {"bc20", INI_STRING}, {"9737", INI_STRING}, {"5e0b", INI_STRING},  \
        {"bb70", INI_STRING}, {"2c2a", INI_STRING}, {"1141", INI_STRING}, {"1c5c", INI_STRING}, {"f876", INI_STRING},  \
        {"a939", INI_STRING}, {"8c00", INI_STRING}, {"ea13", INI_STRING}, {"836d", INI_STRING}, {"c15c", INI_STRING},  \
        {"60f3", INI_STRING}, {"1b93", INI_STRING}, {"5a01", INI_STRING}, {"eb57", INI_STRING}, {"360a", INI_STRING},  \
        {"16f4", INI_STRING}, {"7101", INI_STRING}, {"c366", INI_STRING}, {"36f9", INI_STRING},
