include(versions)
include(FetchContent)

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/dependencies/${SDL2_MIXER_FILE})
	file(${SDL2_MIXER_HASH_TYPE} ${CMAKE_CURRENT_SOURCE_DIR}/dependencies/${SDL2_MIXER_FILE} SDL2_MIXER_FILE_HASH)

	if(${SDL2_MIXER_FILE_HASH} STREQUAL ${SDL2_MIXER_HASH})
		set(SDL2_MIXER_URI file://${CMAKE_CURRENT_SOURCE_DIR}/dependencies/${SDL2_MIXER_FILE})
	endif()
endif()

FetchContent_Declare(
	SDL2_MIXER
	TIMEOUT 60
	URL ${SDL2_MIXER_URI}
	URL_HASH ${SDL2_MIXER_HASH_TYPE}=${SDL2_MIXER_HASH}
	DOWNLOAD_EXTRACT_TIMESTAMP FALSE
	OVERRIDE_FIND_PACKAGE
)

set(SDL2MIXER_DEPS_SHARED OFF)
set(SDL2MIXER_SAMPLES OFF)
set(SDL2MIXER_CMD OFF)
set(SDL2MIXER_FLAC OFF)
set(SDL2MIXER_MOD OFF)
set(SDL2MIXER_MP3 OFF)
set(SDL2MIXER_MIDI OFF)
set(SDL2MIXER_OPUS OFF)
set(SDL2MIXER_VORBIS OFF)
set(SDL2MIXER_INSTALL OFF)

FetchContent_MakeAvailable(SDL2_MIXER)
