include(versions)
include(FetchContent)

if(EXISTS ${CMAKE_CURRENT_SOURCE_DIR}/dependencies/${UTF8PROC_FILE})
	file(${UTF8PROC_HASH_TYPE} ${CMAKE_CURRENT_SOURCE_DIR}/dependencies/${UTF8PROC_FILE} UTF8PROC_FILE_HASH)

	if(${UTF8PROC_FILE_HASH} STREQUAL ${UTF8PROC_HASH})
		set(UTF8PROC_URI file://${CMAKE_CURRENT_SOURCE_DIR}/dependencies/${UTF8PROC_FILE})
	endif()
endif()

FetchContent_Declare(
	UTF8PROC
	TIMEOUT 60
	URL ${UTF8PROC_URI}
	URL_HASH ${UTF8PROC_HASH_TYPE}=${UTF8PROC_HASH}
	DOWNLOAD_EXTRACT_TIMESTAMP FALSE
	OVERRIDE_FIND_PACKAGE
)

set(UTF8PROC_INSTALL Off)

FetchContent_MakeAvailable(UTF8PROC)
