name: Build Workflow
on:
   push:
      branches:
      - master
      paths-ignore:
      - '**.md'
      - '**.yml'
      - '**/doc'

   pull_request:
      types:
      - opened
      - synchronize
      - reopened
      paths-ignore:
      - '**.md'
      - '**.yml'
      - '**/doc'

jobs:
   Linux-i386:
      runs-on: ubuntu-22.04

      env:
         BUILD_DIR: build
         BUILD_TYPE: Debug

      steps:
      -  name: Setup Dependencies
         run: |
            sudo dpkg --add-architecture i386
            sudo apt-get update -y -qq
            sudo apt-get install -y -qq build-essential gcc-multilib g++-multilib libsdl2-dev:i386 libsdl2-mixer-dev:i386 libsdl2-net-dev:i386 libsdl2-ttf-dev:i386 ninja-build:i386

      -  name: Checkout
         uses: actions/checkout@v3

      -  name: Build
         run: |-
            mkdir $BUILD_DIR
            cd $BUILD_DIR
            cmake -G "Ninja" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX=/usr/local ..
            cmake --build . --parallel

      -  name: Package
         run: |
            cd $BUILD_DIR
            cpack --config CPackConfig.cmake
            cpack --config CPackSourceConfig.cmake
            mkdir Artifacts
            cp *.deb Artifacts/
            cp *.tar.gz Artifacts/

      -  name: Upload Artifacts
         uses: actions/upload-artifact@v3
         with:
            name: build artifacts
            path: ${{env.BUILD_DIR}}/Artifacts

   Windows-i386:
      runs-on: windows-2019
      env:
         BUILD_DIR: build
         BUILD_TYPE: Debug

      defaults:
         run:
            shell: msys2 {0}

      steps:
      -  name: Install MSYS2
         uses: msys2/setup-msys2@v2
         with:
            msystem: MINGW32

      -  name: Setup Dependencies
         run: |
            pacman -S --noconfirm git mingw-w64-i686-toolchain mingw32/mingw-w64-i686-SDL2 mingw32/mingw-w64-i686-SDL2_mixer mingw32/mingw-w64-i686-SDL2_net mingw32/mingw-w64-i686-SDL2_ttf mingw32/mingw-w64-i686-cmake mingw-w64-x86_64-ninja make

      -  name: Checkout
         uses: actions/checkout@v3

      -  name: Build
         run: |-
            export PATH=$PATH:/mingw32/bin
            mkdir $BUILD_DIR
            cd $BUILD_DIR
            cmake -G "Ninja" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DCMAKE_INSTALL_PREFIX="C:/Program Files (x86)/max" ..
            cmake --build . --parallel


      -  name: Package
         run: |
            cd $BUILD_DIR
            cpack --config CPackConfig.cmake
            cpack --config CPackSourceConfig.cmake
            mkdir Artifacts
            cp *-win32.exe Artifacts/
            cp *-Source.7z Artifacts/

      -  name: Upload Artifacts
         uses: actions/upload-artifact@v3
         with:
            name: build artifacts
            path: ${{env.BUILD_DIR}}/Artifacts