name: Release Workflow
on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  Linux-i386:
    runs-on: ubuntu-latest

    steps:
    - name: Release Package
      id: create_release
      if: startsWith(github.event.ref, 'refs/tags')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      with:
        tag_name: ${{github.ref}}
        release_name: Release ${{github.ref}}
        draft: false
        prerelease: false
